AWSTemplateFormatVersion: 2010-09-09
Description: |
  This templates creates an EC2 Instance to run dynamic web site with flask web frame
Parameters: #instance type tanimlanacak, Keyname tanimlanacak

Mappings: #completed
  RegionImageMap:
    us-east-1:
      AMI: ami-0c94855ba95c71c99
    us-east-2:
      AMI: ami-0603cbe34fd08cb81
    us-west-1:
      AMI: ami-0e65ed16c9bf1abc7
    us-west-2:
      AMI: ami-0841edc20334f9287
    eu-west-1:
      AMI: ami-08a2aed6e0a6f9c7d
  
Resources:
  MyEc2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap 
        - RegionImageMap
        - !Ref AWS::Region 
        - AMI 
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroups
      SecurityGroups:
        - String
      SourceDestCheck: Boolean
      SsmAssociations:
        - SsmAssociation
      SubnetId: String
      Tags:
        - Tag
      Tenancy: String
      UserData: String
      Volumes:
        - Volume
  

  #completed
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP and SSH Connections #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  
  
